# Generated by Django 5.2.1 on 2025-05-30 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diretoria',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='diretoria',
            name='sociedade',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='Diretoria',
        ),
        migrations.DeleteModel(
            name='Sociedade',
        ),
    ]
