# Generated by Django 5.2.1 on 2025-05-31 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_diretoria_pessoa_remove_diretoria_sociedade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagemcontato',
            old_name='duvida',
            new_name='mensagem',
        ),
        migrations.RemoveField(
            model_name='mensagemcontato',
            name='data_envio',
        ),
    ]
